=== naseem91/SpeechRecorderSBT/speechrecorder/src/main/java/ipsk/apps/speechrecorder/SpeechRecPrompts.dtd
<!ELEMENT session (metadata?, recordingscript)><!ELEMENT script (metadata?, recordingscript)><!ATTLIST session id CDATA #REQUIRED><!ATTLIST script id CDATA #REQUIRED><!ELEMENT metadata (key, value)+><!ELEMENT key (#PCDATA)><!ELEMENT value (#PCDATA)*><!ELEMENT recordingscript (section)+><!ATTLIST section name CDATA #IMPLIED                  speakerdisplay CDATA #IMPLIED                  order CDATA #IMPLIED                  mode CDATA #IMPLIED                  promptphase CDATA #IMPLIED><!ELEMENT section (nonrecording | recording)+><!ELEMENT nonrecording (mediaitem)><!ELEMENT recording (recinstructions?, recprompt, reccomment?) ><!ATTLIST recording	itemcode CDATA #REQUIRED					recduration CDATA #REQUIRED					prerecdelay CDATA #IMPLIED					postrecdelay CDATA #IMPLIED					finalsilence CDATA #IMPLIED					beep CDATA #IMPLIED					rectype CDATA #IMPLIED><!ELEMENT recinstructions (#PCDATA) ><!ATTLIST recinstructions	mimetype CDATA #IMPLIED							src CDATA #IMPLIED><!ELEMENT recprompt (mediaitem)><!ELEMENT reccomment (#PCDATA)><!ELEMENT mediaitem (#PCDATA)*><!ATTLIST mediaitem	mimetype CDATA #IMPLIED					src CDATA #IMPLIED					alt CDATA #IMPLIED					autoplay CDATA #IMPLIED					modal CDATA #IMPLIED					width CDATA #IMPLIED					height CDATA #IMPLIED					volume CDATA #IMPLIED>

=== naseem91/SpeechRecorderSBT/speechrecorder/target/scala-2.12/classes/ipsk/apps/speechrecorder/ExampleRecScript.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?><!DOCTYPE script SYSTEM "SpeechRecPrompts.dtd">
<script id="Example script">
	<metadata>		<key>			DatabaseName		</key>		<value>			SpeechRecorder Demonstration		</value>		<key>			ScriptName		</key>		<value>			SpeechRecorder Sample Recording Script		</value>		<key>			ScriptAuthor		</key>		<value>			Chr. Draxler, Phonetics Institute, University of Munich		</value>		<key>			EmailAuthor		</key>		<value>			draxler@phonetik.uni-muenchen.de		</value>	</metadata>	<recordingscript>		<section name="Introduction" order="sequential" speakerdisplay="no" mode="manual" promptphase="idle">				<recording  prerecdelay="2000" recduration="20000" postrecdelay="500" itemcode="demo_000">			<recprompt>				<mediaitem mimetype="text/UTF-8">					Welcome to the SpeechRecorder Demo Script.				</mediaitem>			</recprompt>		</recording>		<recording  prerecdelay="2000" recduration="20000" postrecdelay="500" itemcode="demo_001">			<recinstructions mimetype="text/UTF-8">				Here you'll find the instructions...			</recinstructions>			<recprompt>				<mediaitem mimetype="text/UTF-8">					and here is the prompt: a text to read, a question to answer, a picture to describe, or something completely different.				</mediaitem>			</recprompt>		</recording>		<recording  prerecdelay="2000" recduration="20000" postrecdelay="500" itemcode="demo_002">			<recprompt>				<mediaitem mimetype="text/UTF-8">					The recording script is divided into sections. In this introductory section,					no speaker display is shown and the prompt items appear in the order					in which they are in the recording script file. 				</mediaitem>			</recprompt>		</recording>		<recording  prerecdelay="2000" recduration="20000" postrecdelay="500" itemcode="demo_003">			<recprompt>				<mediaitem mimetype="text/UTF-8">					In the next section, a speaker display will appear, 					the recordings progress automatically, and 					the items are selected in random order.				</mediaitem>			</recprompt>		</recording>				</section>		<section name="Recording Session" order="random" speakerdisplay="yes" mode="autoprogress" promptphase="idle">				<recording  prerecdelay="2000" recduration="20000" postrecdelay="500" itemcode="demo_010">			<recinstructions mimetype="text/ISO-8859-1">				Please read the digits			</recinstructions>			<recprompt>				<mediaitem mimetype="text/UTF-8">					2 7 4 1 6 8 3 9 5 0				</mediaitem>			</recprompt>		</recording>		<recording  prerecdelay="2000" recduration="60000" postrecdelay="500" itemcode="demo_012">			<recinstructions mimetype="text/ISO-8859-1">				Please answer			</recinstructions>			<recprompt>				<mediaitem mimetype="text/UTF-8">					How did you get here today?				</mediaitem>			</recprompt>		</recording>		<recording  prerecdelay="2000" recduration="10000" postrecdelay="500" itemcode="demo_013">			<recinstructions mimetype="text/UTF-8">				Please read the bi-lingual sentence			</recinstructions>			<recprompt>				<mediaitem mimetype="text/UTF-8">					And then he said to me: "もう一度ダイヤルします"				</mediaitem>			</recprompt>			<reccomment>				Expected pronunciation: mou ichido DIAL shimasu			</reccomment>		</recording>		<recording  prerecdelay="2000" recduration="20000" postrecdelay="500" itemcode="demo_020">			<recinstructions mimetype="text/ISO-8859-1">				Bitte antworten Sie			</recinstructions>			<recprompt>				<mediaitem mimetype="text/UTF-8">					Wie heißen Sie?				</mediaitem>			</recprompt>		</recording>		<!-- Uncomment the following item to see an image prompt. 			 Note that this requires access to the Internet. 			 Please make sure you are connected to the Internet. -->		<!--		<recording  prerecdelay="2000" recduration="60000" postrecdelay="500" itemcode="demo_021">			<recinstructions mimetype="text/UTF-8">				Describe the picture			</recinstructions>			<recprompt>				<mediaitem mimetype="image/jpeg" src="http://www.phonetik.uni-muenchen.de/Bas/software/speechrecorder/prompts/image/FelixWas.jpg" alt="Boy and washing machine">					Boy staring into washing machine in operation				</mediaitem>			</recprompt>			<reccomment>				If the picture does not show, please make sure that you have an active Internet connection.			</reccomment>		</recording>		-->		<recording  prerecdelay="2000" recduration="10000" postrecdelay="500" itemcode="demo_022">			<recinstructions mimetype="text/ISO-8859-1">				Bitte ergänzen Sie			</recinstructions>			<recprompt>				<mediaitem mimetype="text/UTF-8">					Morgenstund hat ...				</mediaitem>			</recprompt>		</recording>		<recording  prerecdelay="2000" recduration="60000" postrecdelay="500" itemcode="demo_030">			<recinstructions mimetype="text/ISO-8859-1">				Répondez s'il vous plaît			</recinstructions>			<recprompt>				<mediaitem mimetype="text/UTF-8">					Qu'est-ce que vous avez fait hier soir?				</mediaitem>			</recprompt>			<reccomment>				Answer expected in French; one minute recording time			</reccomment>		</recording>		<recording  prerecdelay="2000" recduration="10000" postrecdelay="500" itemcode="demo_031">			<recinstructions mimetype="text/ISO-8859-1">				Lisez la phrase			</recinstructions>			<recprompt>				<mediaitem mimetype="text/UTF-8">					A Paris il y a 14 lignes de métro dont 9 traversent la Seine.				</mediaitem>			</recprompt>			<reccomment>				French sentence: In Paris there are 14 metro lines, 9 of which cross the Seine.			</reccomment>		</recording>		<recording  prerecdelay="2000" recduration="10000" postrecdelay="500" itemcode="demo_040">			<recinstructions mimetype="text/ISO-8859-1">				Var snäll och läs			</recinstructions>			<recprompt>				<mediaitem mimetype="text/UTF-8">					Det är vackert vårväder idag				</mediaitem>			</recprompt>			<reccomment>				Swedish sentence: Today is nice Spring weather.			</reccomment>		</recording>		<recording  prerecdelay="2000" recduration="10000" postrecdelay="500" itemcode="demo_041">			<recinstructions mimetype="text/ISO-8859-1">				Var snäll och bokstavera			</recinstructions>			<recprompt>				<mediaitem mimetype="text/UTF-8">					M O R G O N S T U N D				</mediaitem>			</recprompt>			<reccomment>				Swedish spelling			</reccomment>		</recording>		<recording  prerecdelay="2000" recduration="10000" postrecdelay="500" itemcode="demo_042">			<recinstructions mimetype="text/ISO-8859-1">				Var snäll och svara på följande fråga			</recinstructions>			<recprompt>				<mediaitem mimetype="text/UTF-8">					Vad har du gjort under den senaste timmen?				</mediaitem>			</recprompt>			<reccomment>				Swedish question: What did you do during the past hour?			</reccomment>		</recording>		<recording  prerecdelay="2000" recduration="10000" postrecdelay="500" itemcode="demo_050">			<recinstructions mimetype="text/UTF-8">				Lue			</recinstructions>			<recprompt>				<mediaitem mimetype="text/UTF-8">					Maanantai 24. huhtikuuta 2005				</mediaitem>			</recprompt>			<reccomment>				Finnish date phrase			</reccomment>		</recording>		<recording  prerecdelay="2000" recduration="10000" postrecdelay="500" itemcode="demo_051">			<recinstructions mimetype="text/UTF-8">				Vastaa kysymykseen			</recinstructions>			<recprompt>				<mediaitem mimetype="text/UTF-8">					Mikä on nimesi?				</mediaitem>			</recprompt>			<reccomment>				Finnish question: What is your name?			</reccomment>		</recording>		<recording  prerecdelay="2000" recduration="60000" postrecdelay="500" itemcode="demo_052">			<recinstructions mimetype="text/UTF-8">				Vastaa kysymykseen			</recinstructions>			<recprompt>				<mediaitem mimetype="text/UTF-8">					Mitä syöt mieluiten aamiaiseksi? (sinulla on yksi minuutti aikaa)				</mediaitem>			</recprompt>			<reccomment>				Finnish question: What do you like best for breakfast?			</reccomment>		</recording>		<recording  prerecdelay="2000" recduration="10000" postrecdelay="500" itemcode="demo_061">			<recinstructions mimetype="text/UTF-8">				Παρακαλώ διαβάστε			</recinstructions>			<recprompt>				<mediaitem mimetype="text/UTF-8">					Δευτέρα, 24 Απριλίου 2005				</mediaitem>			</recprompt>			<reccomment>				Greek date phrase			</reccomment>		</recording>		<recording  prerecdelay="2000" recduration="10000" postrecdelay="500" itemcode="demo_062">			<recinstructions mimetype="text/UTF-8">				Παρακαλώ ολοκληρώστε			</recinstructions>			<recprompt>				<mediaitem mimetype="text/UTF-8">					Κύλησε ο τέντζερης και ....				</mediaitem>			</recprompt>			<reccomment>				Greek pro-verb completion task.			</reccomment>		</recording>		<recording  prerecdelay="2000" recduration="10000" postrecdelay="500" itemcode="demo_063">			<recinstructions mimetype="text/UTF-8">				Παρακαλώ απαντήστε στην ερώτηση			</recinstructions>			<recprompt>				<mediaitem mimetype="text/UTF-8">					Τι κάνατε την τελευταία ώρα;				</mediaitem>			</recprompt>			<reccomment>				Greek question: what did you do during the past hour?			</reccomment>		</recording>		</section>			</recordingscript></script>
